import type { MetadataRoute } from 'next'

const BASE = 'https://pilot.quantflow.studio'

const pages = [
  { path: '', priority: 1.0, changeFrequency: 'weekly' as const },
  { path: '/getting-started/prerequisites', priority: 0.9, changeFrequency: 'monthly' as const },
  { path: '/getting-started/installation', priority: 0.9, changeFrequency: 'monthly' as const },
  { path: '/getting-started/quickstart', priority: 0.9, changeFrequency: 'monthly' as const },
  { path: '/getting-started/configuration', priority: 0.9, changeFrequency: 'monthly' as const },
  { path: '/navigator', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/navigator/how-it-works', priority: 0.7, changeFrequency: 'monthly' as const },
  { path: '/navigator/setup', priority: 0.7, changeFrequency: 'monthly' as const },
  { path: '/navigator/best-practices', priority: 0.7, changeFrequency: 'monthly' as const },
  { path: '/features/autopilot', priority: 0.8, changeFrequency: 'monthly' as const },
  { path: '/features/hooks', priority: 0.7, changeFrequency: 'monthly' as const },
  { path: '/features/epic-decomposition', priority: 0.7, changeFrequency: 'monthly' as const },
  { path: '/features/dashboard', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/features/hot-upgrade', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/features/quality-gates', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/features/self-healing', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/features/alerts', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/features/autopilot-environments', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/features/budget', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/effort-routing', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/evaluation-system', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/execution-modes', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/memory', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/telegram', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/approval-workflows', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/github', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/replay', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/self-improvement', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/features/teams', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/integrations/github', priority: 0.7, changeFrequency: 'monthly' as const },
  { path: '/integrations/gitlab', priority: 0.7, changeFrequency: 'monthly' as const },
  { path: '/integrations/linear', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/integrations/jira', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/integrations/slack', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/integrations/telegram', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/integrations/discord', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/integrations/asana', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/integrations/azure-devops', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/integrations/plane', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/concepts/architecture', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/concepts/execution-pipeline', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/concepts/adapters', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/concepts/model-routing', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/concepts/execution-backends', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/concepts/worktree-isolation', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/concepts/why-pilot', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/deployment', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/deployment/local', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/deployment/docker', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/deployment/docker-helm', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/deployment/kubernetes', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/deployment/aws', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/deployment/azure', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/deployment/google-cloud', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/deployment/desktop-app', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/deployment/monitoring', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/deployment/networking', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/cli/commands', priority: 0.6, changeFrequency: 'monthly' as const },
  { path: '/cli/doctor', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/guides/multi-repo', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/guides/troubleshooting', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/guides/tunnel-setup', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/guides/custom-providers', priority: 0.5, changeFrequency: 'monthly' as const },
  { path: '/community', priority: 0.5, changeFrequency: 'monthly' as const },
]

export default function sitemap(): MetadataRoute.Sitemap {
  return pages.map(({ path, priority, changeFrequency }) => ({
    url: `${BASE}${path}`,
    priority,
    changeFrequency,
  }))
}
