import type { MetadataRoute } from 'next'

const BASE = 'https://pilot.quantflow.studio'

// Static priority map — high-traffic pages get higher priority
const PRIORITY: Record<string, number> = {
  '': 1.0,
  '/getting-started/prerequisites': 0.9,
  '/getting-started/quickstart': 0.9,
  '/getting-started/installation': 0.9,
  '/getting-started/configuration': 0.8,
  '/features/autopilot': 0.8,
  '/features/hooks': 0.7,
  '/features/epic-decomposition': 0.7,
  '/navigator': 0.7,
}

const ROUTES = [
  '',
  '/getting-started/prerequisites',
  '/getting-started/installation',
  '/getting-started/quickstart',
  '/getting-started/configuration',
  '/features/autopilot',
  '/features/autopilot-environments',
  '/features/approval-workflows',
  '/features/alerts',
  '/features/budget',
  '/features/dashboard',
  '/features/effort-routing',
  '/features/epic-decomposition',
  '/features/evaluation-system',
  '/features/execution-modes',
  '/features/executor-mode-signal',
  '/features/github',
  '/features/hooks',
  '/features/hot-upgrade',
  '/features/memory',
  '/features/quality-gates',
  '/features/replay',
  '/features/self-healing',
  '/features/self-improvement',
  '/features/teams',
  '/features/telegram',
  '/navigator',
  '/navigator/how-it-works',
  '/navigator/setup',
  '/navigator/best-practices',
  '/concepts/architecture',
  '/concepts/adapters',
  '/concepts/execution-pipeline',
  '/concepts/execution-backends',
  '/concepts/model-routing',
  '/concepts/signal-parser',
  '/concepts/why-pilot',
  '/concepts/worktree-isolation',
  '/integrations/github',
  '/integrations/gitlab',
  '/integrations/linear',
  '/integrations/jira',
  '/integrations/asana',
  '/integrations/azure-devops',
  '/integrations/plane',
  '/integrations/slack',
  '/integrations/telegram',
  '/integrations/discord',
  '/deployment',
  '/deployment/local',
  '/deployment/docker',
  '/deployment/docker-helm',
  '/deployment/kubernetes',
  '/deployment/aws',
  '/deployment/azure',
  '/deployment/google-cloud',
  '/deployment/monitoring',
  '/deployment/networking',
  '/deployment/desktop-app',
  '/cli/commands',
  '/cli/doctor',
  '/guides/multi-repo',
  '/guides/custom-providers',
  '/guides/tunnel-setup',
  '/guides/troubleshooting',
  '/community',
]

export default function sitemap(): MetadataRoute.Sitemap {
  return ROUTES.map((route) => ({
    url: `${BASE}${route}`,
    changeFrequency: 'weekly' as const,
    priority: PRIORITY[route] ?? 0.6,
  }))
}
